name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-heroicon-main-ruby-3.0.x-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler:2.2.33
          bundle install --jobs 4 --retry 3
      - name: Lint
        run: bundle exec rubocop --parallel

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.7, 3.0]
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-heroicon-main-ruby-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler:2.2.33
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake
