name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Tests
        run: bundle exec rake
